name = "whaletrucker-reef"
type = "javascript"
account_id = "1bbd219c23dd03cc764c159bfe42e649"
workers_dev = true
compatibility_date = "2025-12-08"

kv_namespaces = [
  { binding = "WHALETRUCKER_REEF_KV", id = "95d133e1ead4aac9cfa649120564f1e" }
]
